ALTER TABLE customers ALTER COLUMN CustomerID ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE orders ALTER COLUMN OrderID ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE categories ALTER COLUMN CategoryID ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE shipments ALTER COLUMN ShipmentID ADD GENERATED ALWAYS AS IDENTITY;
